### ISSUE TITLE
Refer to appropriate section for clarity

### ISSUE THREAD

**Issue by jtheinen** [mechmotum/ollie-optimization#47]
Reviewer 2:
1.  [“We solved the base skateboard OCP to demonstrate that the model and optimization methodology produce ollies with realistic kinematics and kinetics.”](https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L351)

Refer to the section where we describe the criterion to conclude this.

2. [“To demonstrate simultaneously solving for the control trajectories and optimizing the geometry parameters we present two single parameter optimizations: skateboards 3 and 4 which have their wheelbase and taillength optimized, respectively,”](https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L353)

Refer to figure

3. [“skateboard 5 which demonstrates a multiple parameter optimization involving the simultaneous optimization of wheelbase, deck length, tail/nose inclination, truck height, and wheel radius.”](https://github.com/mechmotum/ollie-optimization/blob/4d4e603d48c2a35e80c1d6a072766645e2bfddee/paper/ollie-optimization.tex#L353)

Refer to figure

**Comment by moorepants** [comment]
Here is more precisely what the reviewer wrote:

```
    5) 2.8 Optimal Control Scenarios

Cay you here describe the appropriate section?
For example, 
“We solved the base skateboard OCP to demonstrate that the model and optimization methodology produce ollies with realistic kinematics and kinetics.”

What’s a criterion to conclude above?
Probably, the criterion will be discussed later.
If so, please describe here, for example, (see ****).

“To demonstrate simultaneously solving for the control trajectories and optimizing the geometry parameters we present two single parameter optimizations: skateboards 3 and 4 which have their wheelbase and taillength optimized, respectively,”
	
Where are you describing? For example, see ***.


“skateboard 5 which demonstrates a multiple parameter optimization involving the simultaneous optimization of wheelbase, deck length, tail/nose inclination, truck height, and wheel radius.”

Where are you describing? For example, see ***.
```

**Comment by moorepants** [comment]
I'm struggling a bit to understand what they are asking for.

**Comment by moorepants** [comment]
I could not figure out what the "see ***" means. For the first point I changed "realistic kinematics and kinetics" to "We solved the base skateboard OCP to demonstrate that the model and optimization methodology produce ollies with qualitatively similar motion to Fig. 1.", as we don't have an real criteria here that we've defined. We just observe the various aspects of the simulation result and make sure nothing seems out of place.

For the second two points I refer to the rows of table 1 instead of the skateboard number:

"To demonstrate simultaneously solving for the control trajectories and optimizing the geometry parameters we present two single parameter optimizations: rows 3 and 4 in Table 1 which have their wheelbase and tail length optimized, respectively, and row 5 which demonstrates a multiple parameter"
